spring.application.name=Linkhub-backend
#spring.datasource.url=${DB_URL}
#spring.datasource.username=${DB_USERNAME}
#spring.datasource.password=${DB_PASSWORD}
spring.datasource.url=jdbc:postgresql://dpg-d9cv91hkh4rs73cd8uhg-a.oregon-postgres.render.com:5432/linkhub
spring.datasource.username=shopping_db_g4sz_user
spring.datasource.password=St29awq1i9HylRQNoUQoQwiB8zwyq6Re
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
#server.port=${PORT:8080}
server.port=8080